<a href="https://colab.research.google.com/github/ZaremaDibirova/Pandas_practise/blob/main/Practise(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [77]:
df=pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

##apply() metodu

###1-ci yol

In [ ]:
# def son4(x):
#   return str(x)[-4:]

# df['CC Number']=df['CC Number'].apply(son4)
# df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

###2-ci yol

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df['CC Number'].apply(lambda x: str(x)[-4:]).head()

#yadda saxlamaq ucun df['CC Number']=df['CC Number'].apply(lambda x: str(x)[-4:])

0    3410
1    9230
2    1322
3    5994
4    7221
Name: CC Number, dtype: object

###3cu-vektorizasiya edilmis yol

In [ ]:
df['CC Number']=df['CC Number'].astype(str).str[-4:].head()

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [ ]:
# Eger musterinin odediyi mebleg 10  dollardan azdirsa $,10 ve 30 arasindadirsa $$,30dan coxdursa $$$ yaz

In [ ]:
def bill_category(x):
  if x<10:
    return '$'
  elif 10<=x<30:
    return '$$'
  else:
    return '$$$'

df['bill_category']=df['total_bill'].apply(bill_category)

In [ ]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
123,15.95,2.0,Male,No,Thur,Lunch,2,7.98,Christopher Lang,NaN,Thur1992,$$
170,50.81,10.0,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,NaN,Sat1954,$$$
182,45.35,3.5,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,NaN,Sun2337,$$$
11,35.26,5.0,Female,No,Sun,Dinner,4,8.82,Diane Macias,NaN,Sun6686,$$$
220,12.16,2.2,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,NaN,Fri4607,$$

In [ ]:
#2ci yol
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df['bill_category']=df['total_bill'].apply(lambda x: '$' if x < 10 else('$$' if 10<= x < 30 else '$$$'))

In [ ]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5519770449260299,Sat632,$$
225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3579111947217428,Fri6665,$$
28,21.70,4.30,Male,No,Sat,Dinner,2,10.85,David Collier,5529694315416009,Sat3697,$$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,$
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3560782621035582,Sat6683,$$

##3-cu yol

In [8]:
def bill_category_vector(bill):
  category=np.full_like(bill,fill_value='$',dtype='U3')

  category[(bill>10) & (bill<30)]='$$'

  category[bill>=30]='$$$'

  return category

df['bill_category']=bill_category_vector(df['total_bill'])
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863,$$$
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3569262692675583,Sat4750,$$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,30432617123103,Sun9209,$
145,8.35,1.50,Female,No,Thur,Lunch,2,4.18,Amy Young,4285454264477,Thur9331,$
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,Sun3848,$$

In [ ]:
#sutunlarin kvadratini almaq

In [13]:
#1-ci yol
def square(x):
  return x**2

df['tip'].apply(square).head()

0     1.0201
1     2.7556
2    12.2500
3    10.9561
4    13.0321
Name: tip, dtype: float64

In [14]:
#2-ci usul
df['tip'].apply(lambda x: x**2).head()

0     1.0201
1     2.7556
2    12.2500
3    10.9561
4    13.0321
Name: tip, dtype: float64

In [15]:
#3-cu usul vectorized
np.square(df['tip'])

0       1.0201
1       2.7556
2      12.2500
3      10.9561
4      13.0321
        ...
239    35.0464
240     4.0000
241     4.0000
242     3.0625
243     9.0000
Name: tip, Length: 244, dtype: float64

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [19]:
df.sort_values('total_bill',ascending=False).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,$$$

In [22]:
df.sort_values(['total_bill','tip'],ascending=False,inplace=True)

In [23]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,$$$

In [24]:
df.reset_index(drop=True,inplace=True)

In [26]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$

In [27]:
df['price_per_person'].max()

20.27

In [28]:
df['total_bill'].min()

3.07

In [29]:
df['tip'].std()

1.3836381890011826

In [32]:
df['tip'].argmin()

195

In [34]:
df['tip'].argmax()

0

In [35]:
df['price_per_person'].mode()

0     6.71
1    10.14
Name: price_per_person, dtype: float64

In [36]:
df['tip'].median()

2.9

In [41]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [42]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [43]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [44]:
df.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [45]:
df.day.unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [46]:
df.smoker.unique()

array(['Yes', 'No'], dtype=object)

In [47]:
df.day.nunique()

4

In [ ]:
##sex sutunundaki male-i 'm',female-i ise 'f' olaraq goster

In [50]:
#apply metodu
df.sex=df.sex.apply(lambda x: 'M' if x=='Male' else 'F')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bill_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,$$$

In [58]:
#replace metodu
df.sex.replace('Male','m',inplace=True)
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,m,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [60]:
df.sex.replace('Female','F',inplace=True)
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,m,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,m,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,m,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,F,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [62]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [68]:
df.sex.replace(['Female','Male'],['F','M'],inplace=True)
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,M,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,M,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

In [70]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [78]:
#map metodu
df.sex=df.sex.map({'Female':'F', 'Male': 'M'})
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,M,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,M,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,M,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,F,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251